#!/usr/bin/env python3

# Copyright 2025-2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import time, contextlib
import threading
from typing import List, Optional
from collections import deque

import cv2
import numpy as np
import cupy as cp

from dimos.core import Module, In, Out, rpc
from dimos.msgs.geometry_msgs import PoseStamped
from dimos.msgs.sensor_msgs import Image, ImageFormat
from dimos_lcm.sensor_msgs import CameraInfo
from dimos.msgs.std_msgs import Header
from dimos.protocol.tf import TF
from dimos.utils.logging_config import setup_logger
from dimos.protocol.pubsub.shm.ipc_factory import CPU_IPC_Factory, CUDA_IPC_Factory
from dimos.utils.multirate import MultiRateProcessor
from dimos.utils.dask_frame_cluster import SourceActor
from dimos.perception.common.utils import colorize_depth

logger = setup_logger(__name__)


class UnitreeCameraModule(Module):
    """
    Camera module for Unitree Go2 that processes RGB images to generate depth using Metric3D.

    Subscribes to:
        - /video: RGB camera images from Unitree

    Publishes:
        - /go2/color_image: RGB camera images
        - /go2/depth_image: Depth images generated by Metric3D
        - /go2/depth_colorized: Colorized depth images with statistics overlay
        - /go2/camera_info: Camera calibration information
        - /go2/camera_pose: Camera pose from TF lookup
    """

    # LCM inputs
    video: In[Image] = None

    # LCM outputs
    color_image: Out[Image] = None
    depth_image: Out[Image] = None
    depth_colorized: Out[Image] = None
    camera_info: Out[CameraInfo] = None
    camera_pose: Out[PoseStamped] = None

    def __init__(
        self,
        camera_intrinsics: List[float],
        world_frame_id: str = "world",
        camera_frame_id: str = "camera_link",
        base_frame_id: str = "base_link",
        gt_depth_scale: float = 2.0,
        **kwargs,
    ):
        """
        Initialize Unitree Camera Module.

        Args:
            camera_intrinsics: Camera intrinsics [fx, fy, cx, cy]
            camera_frame_id: TF frame ID for camera
            base_frame_id: TF frame ID for robot base
        """
        super().__init__(**kwargs)

        if len(camera_intrinsics) != 4:
            raise ValueError("Camera intrinsics must be [fx, fy, cx, cy]")

        self.camera_intrinsics = camera_intrinsics
        self.camera_frame_id = camera_frame_id
        self.base_frame_id = base_frame_id
        self.world_frame_id = world_frame_id
        self.gt_depth_scale = gt_depth_scale

        # Initialize Metric3D
        from dimos.models.depth.metric3d import Metric3D

        self.metric3d = Metric3D(camera_intrinsics=self.camera_intrinsics)
        self.tf = TF()

        # Processing state
        self._running = False
        self._latest_frame = None
        self._last_image = None
        self._last_depth = None
        self._cannot_process_depth = False

        # IPC & processor members
        self.backend = self._autodetect_backend()
        self._source: Optional[SourceActor] = None  # owns the channel
        self._desc: Optional[dict] = None  # descriptor from source.channel
        self.slot = None  # attached reader for MRP
        self._multirateprocessor: Optional[MultiRateProcessor] = None

        self._depth_pipeline_timestamps = deque(maxlen=60)
        self._latency_window = deque(maxlen=50)  # rolling average over last 50 frames
        self._fps_depth = 0.0

        # Threading
        self._processing_thread: Optional[threading.Thread] = None
        self._stop_processing = threading.Event()

        logger.info(
            f"UnitreeCameraModule initialized | intrinsics={camera_intrinsics} | backend={self.backend}"
        )

    def _autodetect_backend(self) -> str:
        try:
            import cupy as cp  # noqa

            return "cuda" if cp.is_available() else "cpu"
        except Exception:
            return "cpu"

    @rpc
    def start(self):
        """Start the camera module."""
        if self._running:
            logger.warning("Camera module already running")
            return

        self._running = True
        self.video.subscribe(self._on_video)
        self._start_processing_thread()
        logger.info("Camera module started")

    @rpc
    def stop(self):
        """Stop the camera module."""
        if not self._running:
            return

        self._running = False
        self._stop_processing.set()

        # Stop thread
        if self._processing_thread and self._processing_thread.is_alive():
            self._processing_thread.join(timeout=2.0)

        # Stop processor
        try:
            if self._multirateprocessor:
                self._multirateprocessor.stop()
        except Exception:
            pass

        # Close attached slot
        try:
            if self.slot:
                if not (self._source and self.slot is getattr(self._source, "channel", None)):
                    self.slot.close()
        except Exception:
            pass

        # Close source (owner of the channel)
        try:
            if self._source:
                self._source.close()
        except Exception:
            pass

        logger.info("Camera module stopped")

    @rpc
    def get_channel_desc(self) -> dict:
        """Expose the frame channel descriptor so external actors can attach."""
        return self._desc if self._desc is not None else {}

    def _on_video(self, msg: Image):
        """Store latest video frame and feed into IPC via SourceActor."""
        if not self._running:
            return

        try:
            arrival_time = time.time()
            logger.info(f"Frame IN at {arrival_time:.6f}")
            if self._source is None:
                # First frame → initialize SourceActor (owner of channel)
                shape = tuple(msg.data.shape)  # (H, W, C) expected
                prefer = "cuda" if self.backend == "cuda" else "cpu"
                dtype = msg.data.dtype

                # 1) Create SourceActor that OWNS the channel
                self._source = SourceActor(shape=shape, dtype=dtype, prefer=prefer, device_id=0)

                # 2) Same-process fast-path: use the SourceActor's channel directly (no IPC attach)
                self.slot = self._source.channel

                # 3) Build processor on the attached reader slot
                self._multirateprocessor = MultiRateProcessor(
                    channel=self.slot,
                    target_fps_by_model={"depth": 30},
                    handlers={"depth": self._process_depth},
                    max_age_s=0.1,
                )
                self._multirateprocessor.start()

                logger.info(
                    f"Initialized SourceActor + IPC channel shape={shape} prefer={prefer} dtype={dtype}"
                )

            # Push this frame into the channel via SourceActor
            start = time.time()
            self._process_depth(cp.asarray(msg.data) if self.backend == "cuda" else msg.data)
            # self._source.publish(cp.asarray(msg.data) if self.backend == "cuda" else msg.data)
            end = time.time()
            logger.info(
                f"self.source_publish returned. Time: {end}. Time taken: {end - start:.4f} seconds"
            )

            # Keep last image for publishing (color topic)
            self._last_image = cp.asarray(msg.data) if self.backend == "cuda" else msg.data

        except Exception as e:
            logger.error(f"Error in _on_video: {e}", exc_info=True)

    def _start_processing_thread(self):
        """Start an idle processing thread (keeps module lifecycle/simple shutdown)."""
        self._stop_processing.clear()
        self._processing_thread = threading.Thread(target=self._main_processing_loop, daemon=True)
        self._processing_thread.start()
        logger.info("Started camera processing thread")

    def _main_processing_loop(self):
        """Idle loop; MultiRateProcessor pulls frames from IPC and calls our handler."""
        logger.info("Main processing loop running")
        while not self._stop_processing.is_set():
            time.sleep(0.001)

        logger.info("Main processing loop stopped")

    def _process_depth(self, img_array: np.ndarray):
        """Process depth estimation using Metric3D."""
        if self._cannot_process_depth:
            self._last_depth = None
            return

        try:
            frame_start = time.time()
            logger.info(f"Frame PROCESS START {frame_start:.6f}")

            depth_array = (
                self.metric3d.infer_depth(
                    cp.asarray(img_array) if self.backend == "cuda" else img_array
                )
                / self.gt_depth_scale
            )
            self._last_depth = depth_array

            logger.info(f"Frame PROCESS END {time.time():.6f}")

            self._publish_synchronized_data()
            frame_end = time.time()
            logger.info(f"Frame COMPLETE latency={(frame_end - frame_start) * 1000:.1f} ms")

            self._latency_window.append((frame_end - frame_start))

            if len(self._latency_window) > 0:
                avg_latency = sum(self._latency_window) / len(self._latency_window)
                fps = 1.0 / avg_latency if avg_latency > 0 else 0.0
                logger.info(
                    f"End-to-end FPS (latency-based): {fps:.2f}, avg latency={avg_latency * 1000:.1f} ms"
                )

            # --- FPS counter over sliding window ---
            now = time.time()
            self._depth_pipeline_timestamps.append(now)
            if len(self._depth_pipeline_timestamps) >= 2:
                elapsed = self._depth_pipeline_timestamps[-1] - self._depth_pipeline_timestamps[0]
                if elapsed > 0:
                    self._pipeline_fps = (len(self._depth_pipeline_timestamps) - 1) / elapsed
                    logger.info(f"Throughput end-to-end FPS: {self._pipeline_fps:.2f}")

        except Exception as e:
            logger.error(f"Error processing depth: {e}", exc_info=True)
            self._cannot_process_depth = True

    def _publish_synchronized_data(self):
        """Publish color, depth, colorized depth, camera info, and pose."""
        if not self._running:
            return

        try:
            header = Header(self.camera_frame_id)

            publish_start = time.perf_counter()

            """
            # Publish color image (if available)
            if self._last_image is not None:
                color_msg = Image(
                    data=self._last_image,
                    format=ImageFormat.RGB,
                    frame_id=header.frame_id,
                    ts=header.ts,
                )
                self.color_image.publish(color_msg)
                color_end = time.perf_counter()
                logger.info(f"Color publish: {(color_end - publish_start) * 1000:.1f}ms")
            """

            # Publish depth + colorized
            if self._last_depth is not None:
                depth_msg = Image(
                    data=self._last_depth,
                    format=ImageFormat.DEPTH,
                    frame_id=header.frame_id,
                    ts=header.ts,
                )
                logger.info(f"Depth MSG is CUDA? {depth_msg.is_cuda}")
                self.depth_image.publish(
                    depth_msg.as_cuda_ipc_bytes()
                    if depth_msg.is_cuda
                    else depth_msg.as_memoryview()
                )
                depth_end = time.perf_counter()
                logger.info(f"Depth publish: {(depth_end - publish_start) * 1000:.1f}ms")

                """
                depth_colorized_array = colorize_depth(
                    cp.asnumpy(self._last_depth) if self.backend == "cuda" else self._last_depth, max_depth=10.0, overlay_stats=True
                )
                if depth_colorized_array is not None:
                    depth_colorized_msg = Image(
                        data=depth_colorized_array,
                        format=ImageFormat.RGB,
                        frame_id=header.frame_id,
                        ts=header.ts,
                    )
                    self.depth_colorized.publish(depth_colorized_msg)
                    colorized_end = time.perf_counter()
                    logger.info(f"Colorized publish: {(colorized_end - depth_end) * 1000:.1f}ms")
                """

            # Camera info & pose
            self._publish_camera_info(header)
            self._publish_camera_pose(header)
            publish_done = time.time()
            logger.info(f"Frame OUT at {publish_done:.6f}")

        except Exception as e:
            logger.error(f"Error publishing synchronized data: {e}", exc_info=True)

    def _publish_camera_info(self, header: Header):
        """Publish camera calibration information."""
        try:
            fx, fy, cx, cy = self.camera_intrinsics
            if self._last_image is None:
                return
            height, width = self._last_image.shape[:2]

            K = [fx, 0, cx, 0, fy, cy, 0, 0, 1]
            D = [0.0] * 5
            R = [1, 0, 0, 0, 1, 0, 0, 0, 1]
            P = [fx, 0, cx, 0, 0, fy, cy, 0, 0, 0, 1, 0]

            msg = CameraInfo(
                D_length=len(D),
                header=header,
                height=height,
                width=width,
                distortion_model="plumb_bob",
                D=D,
                K=K,
                R=R,
                P=P,
                binning_x=0,
                binning_y=0,
            )
            self.camera_info.publish(msg)
        except Exception as e:
            logger.error(f"Error publishing camera info: {e}", exc_info=True)

    def _publish_camera_pose(self, header: Header):
        """Publish camera pose from TF lookup."""
        try:
            transform = self.tf.get(
                parent_frame=self.world_frame_id,
                child_frame=self.camera_frame_id,
                time_point=header.ts,
                time_tolerance=1.0,
            )
            if transform:
                pose_msg = PoseStamped(
                    ts=header.ts,
                    frame_id=self.camera_frame_id,
                    position=transform.translation,
                    orientation=transform.rotation,
                )
                self.camera_pose.publish(pose_msg)
        except Exception as e:
            logger.error(f"Error publishing camera pose: {e}", exc_info=True)

    @rpc
    def get_camera_intrinsics(self) -> List[float]:
        """Get camera intrinsics."""
        return self.camera_intrinsics

    def cleanup(self):
        """Clean up resources on module destruction."""
        self.stop()
        # Metric3D teardown
        self.metric3d.cleanup()
